### ISSUE TITLE
Add Research Question to the README page

### ISSUE THREAD

**Issue by TommasoRabino** [course-dprep/team-project-team_9_group_project#4]
# SOME TIPS: 

1 - [Here you can find a TilburgScienceHub Article where you can find relevent information on how to write a good README page](https://tilburgsciencehub.com/building-blocks/store-and-document-your-data/document-data/readme-best-practices/)

2 - [Here you can find a GitHub page on "writing and formatting syntax in Markdown"](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

**Comment by biancamagalotti** [comment]
In progress - I have made some changes to the README page in the following branch "Issue_3_researchquestion_README"

I have just made a pull request to commit the changes (to be reviewed together with the group in the next coaching session before merging).

**Comment by TommasoRabino** [comment]
Issue completed. 
Pull Request merged. 
Branch "issue_3_add_research_question_to_README deleted.
